### ISSUE TITLE
Scaling of Labels and Lines in Structure Editor

### ISSUE THREAD

**Issue by lithom** [Actelion/openchemlib#103]
When using the structure editor for molecules with labeled atoms, strange scaling of the label text and the line thickness happens when certain atoms are dragged. In cases with multiple labeled atoms and large molecules (macrocycles etc.) this sometimes makes the editing of structures rather difficult.

The following example was created using the substructure editor (from the substructure filter) and pasting a structure containing labeled atoms in the most recent DataWarrior version:

See the following video:

https://github.com/Actelion/openchemlib/assets/38880291/ac13aef3-f2d1-45d5-bdb9-35a3bef4d17b

IDCode:
```
dk\@@DjUg]h]LHJJh`C~bXK`e]ozaepRnw}``
```

**Comment by lithom** [comment]
Today, I investigated the issue, and found that the AVBL (average bond length) is used to scale everything that is painted via the GenericDepictor / AbstractDepictor / ExtendedDepictor. The code for adapting the various different AVBL values is complicated and a bit all over the place.

A simple solution that fixes most of the drawing problems is to add the possibility to add a upper bound in the ExtendedDepictor::paintStructures(GenericDrawContext context) method where the avbl is applied (around Line 270).

If we add the e.g. the hard-coded

avbl = Math.min(avbl,24.0);

to limit the AVBL to 24.0, then editing molecules becomes much more convenient and we get rid of the scaling issues:


https://github.com/Actelion/openchemlib/assets/38880291/3b80c620-fb7f-4461-bcbf-6995c3d9a647


IDCode used in example: eiWXL@@HPDElbfbRrTTRRrbbRbbrRVLrxD|Bf^NAaQyEZ@B`HJ`@HHbZj`B`@@

**Comment by thsa** [comment]
Now we use the median bond length as basis for sizing everything. Now a small number of very long bonds don't change label sizes anymore. Hard coded max bond length are not a good option because of DPI-scaling or printer scaling.
