### ISSUE TITLE
Extra space in RXN v3 ?

### ISSUE THREAD

**Issue by lpatiny** [Actelion/openchemlib#111]
It seems that when we get the RXN v3000 there is an extra space at the beginning of the first line.

@thsa 

```
$RXN V3000


OCL_RXN_V1.0:gJX@@eKU@@ gGQHDHaImfh@!defH@DAIfUVjj`@#IGiYP qDir IjAKiqeP#!R@Fq?[@@S_qL]x`H !RbOs~@Hc}bOrH?QulH` !R?g~w?Xc}m?s~_xc|m?vH?Xc}GYk\##
 M  V30 BEGIN REACTANT
M  V30 BEGIN CTAB
M  V30 COUNTS 6 5 0 0 0
M  V30 BEGIN ATOM
M  V30 1 C 2.369 -9.0416 0 2
M  V30 2 C 3.2351 -8.5416 0 3
M  V30 3 C 4.1011 -9.0416 0 4
```

![image](https://github.com/user-attachments/assets/aea63ab9-51c7-4fac-b883-3a3c7f6a1d33)

**Comment by targos** [comment]
Seems to be a bug here:

https://github.com/Actelion/openchemlib/blob/e8e44d2b735d25314d1bee1b715a0131e56ee332/src/main/java/com/actelion/research/chem/io/RXNFileV3Creator.java#L74

It ends up writing a single space character instead of a COUNTS line.

**Comment by targos** [comment]
@lpatiny The bug is only in the JS version. You can close this issue.
