### ISSUE TITLE
No change in idCode when unknown chirality ?

### ISSUE THREAD

**Issue by lpatiny** [Actelion/openchemlib#112]
@thsa 

I'm wondering if it is normal that if you know ... you don't know the chirality and you specify it using the corresponding tool there is no change in the idCode.

This means that if you reedit the molecule from this oclID you will get again the pink chiral center telling the information is missing.

![2024-07-25 10 45 30](https://github.com/user-attachments/assets/54312da3-263e-4ee2-baba-0f1cbd0fc0b5)

**Comment by thsa** [comment]
that is indeed correct. Within OCL logic (and thus inside idcodes) we distinguish these states of stereo centers: ABS (absolute), AND (racemic), OR (the drawn one or the other), UNKNOWN (no information). For UNKNOWN ist does not make a difference, whether the user provided no information or whether he/she specified that there is no information. The editor, however, should force or at least remind a user to explitily specify that he has no information, therefore the magenta color.
