### ISSUE TITLE
Problem with floating point logic in coordinates encoding

### ISSUE THREAD

**Issue by lithom** [Actelion/openchemlib#116]
There seems to be a small problem with the encoding / decoding of coordinates.

public static void main(String args[]) {
		String idc = "ejYZBD@AELb`PdilPJqbPrJIJEJJJJZKZKJJUJ[RccrHii[[zF@HjZifjih@bXZ@@@";
		IDCodeParser icp = new IDCodeParser();
		StereoMolecule mi = new StereoMolecule();
		for(int zi=0;zi<100;zi++) {
			System.out.println(idc);
			icp.parse(mi,idc);
			idc = mi.getIDCode()+ " "+mi.getIDCoordinates();
		}
	}

results in coordinates that change over time:

ejYZBD@AELb`PdilPJqbPrJIJEJJJJZKZKJJUJ[RccrHii[[zF@HjZifjih@bXZ@@@
ejYZBD@AELb`PdilPJqbPrJIJEJJJJZKZKJJUJ[RccrHii[[zF@HjZifjih@bXZ@@@ !Bmwvw@oy?m?vw?[\B?g~w?_y?bOvw__y?b@Jw?Oy?bOvw__x@mwvw__y??g~w?Oy?mwu??gvHbGvw__y??g~H_[]}b@K~@Ha}
ejYZBD@AELb`PdilPJqbPrJIJEJJJJZKZKJJUJ[RccrHii[[zF@HjZifjih@bXZ@@@ !Bu{wW?Gx?uwwW_]_|_c?W_Wx?bGwWoWx?bOsW?Gx?bGwWoWx@u{wWoWx?_c?W?Gx?u{t?_kvHbKwWoWx?_c~Ho]^}bOq~@Hb}
ejYZBD@AELb`PdilPJqbPrJIJEJJJJZKZKJJUJ[RccrHii[[zF@HjZifjih@bXZ@@@ !BesvW?Ky_e{vWoY_|oe~Wo[y_bKvWO[y_bOrW?Ky_bKvWO[x@esvWO[y_oe~W?Ky_esu_ocvHbCvWO[y_oe~HOY\}bOr~@H`}
ejYZBD@AELb`PdilPJqbPrJIJEJJJJZKZKJJUJ[RccrHii[[zF@HjZifjih@bXZ@@@ !By}wg?Cx_yswgO^_|Oa?gOSx_bCwgwSx_bOsg?Cx_bCwgwSx@y}wgwSx_Oa?g?Cx_y}t_OmvHbMwgwSx_Oa~Hw^_]bOp~@Hc]
ejYZBD@AELb`PdilPJqbPrJIJEJJJJZKZKJJUJ[RccrHii[[zF@HjZifjih@bXZ@@@ !Biuvg?Myoi}vgwZ_|wf~gw]yobMvgW]yobOrg?MyobMvgW]x@iuvgW]yowf~g?MyoiuuowevHbEvgW]yowf~HWZ]]bOs^@Ha]
ejYZBD@AELb`PdilPJqbPrJIJEJJJJZKZKJJUJ[RccrHii[[zF@HjZifjih@bXZ@@@ !BqywG?ExoquwGW\_|Wb?GWUxobEwGgUxobOsG?ExobEwGgUx@qywGgUxoWb?G?ExoqytoWivHbIwGgUxoWb~Hg\^]bOq^@Hb]
ejYZBD@AELb`PdilPJqbPrJIJEJJJJZKZKJJUJ[RccrHii[[zF@HjZifjih@bXZ@@@ !BaqvG?IyOayvGgX_|gd~GgYyObIvGGYyObOrG?IyObIvGGYx@aqvGGYyOgd~G?IyOaquOgavHbAvGGYyOgd~HGX\]bOr^@H`]

Closer investigation identified the two parts of code relevant for floating point encoding / decoding:

Canonizer (around line 3466):

private void encodeCoords(int atom, int from, double maxDeltaPlusHalfIncrement, double increment, int resolutionBits, Coordinates[] coords) {
		double deltaX = (from == -1) ?
						(coords[atom].x - coords[mGraphAtom[0]].x) / 8.0
					   : coords[atom].x - coords[from].x;

		double deltaY = (from == -1) ?
						(coords[atom].y - coords[mGraphAtom[0]].y) / 8.0
					   : coords[atom].y - coords[from].y;

		System.out.println("[ENC] "+ atom+" : "+deltaX+" " +deltaY);

		encodeBits((int)((maxDeltaPlusHalfIncrement + deltaX) / increment), resolutionBits);
		encodeBits((int)((maxDeltaPlusHalfIncrement + deltaY) / increment), resolutionBits);

		if (mZCoordinatesAvailable) {
			double deltaZ = (from == -1) ?
							(coords[atom].z - coords[mGraphAtom[0]].z) / 8.0
						   : coords[atom].z - coords[from].z;

			encodeBits((int)((maxDeltaPlusHalfIncrement + deltaZ) / increment), resolutionBits);
			}
		}

and in IDCodeParserWithoutCoordinateInvention (around line 767):

fixed version (added the +1 to the decodeBits(..) value) :
	double decodedDX = factor * (decodeBits(resolutionBits)+1 - binCount / 2.0);
	double decodedDY = factor * (decodeBits(resolutionBits)+1 - binCount / 2.0);
						//System.out.println("[DEC] "+atom+" : "+decodedDX+" " +decodedDY);
						mMol.setAtomX(atom, mMol.getAtomX(from) + decodedDX);
						mMol.setAtomY(atom, mMol.getAtomY(from) + decodedDY);
						if (coordsAre3D)
							mMol.setAtomZ(atom, mMol.getAtomZ(from) + factor * (decodeBits(resolutionBits) - binCount / 2.0));
						}

It seems that in encoding, the "0" value is encoded to the "126" (i.e. the first negative value), but encoding expects 127 (the first positive value) for zero. Therefore, adding +1 fixes the decoding / encoding.

ejYZBD@AELb`PdilPJqbPrJIJEJJJJZKZKJJUJ[RccrHii[[zF@HjZifjih@bXZ@@@
ejYZBD@AELb`PdilPJqbPrJIJEJJJJZKZKJJUJ[RccrHii[[zF@HjZifjih@bXZ@@@ !Bmwvw@oy?m?vw?[\B?g~w?_y?bOvw__y?b@Jw?Oy?bOvw__x@mwvw__y??g~w?Oy?mwu??gvHbGvw__y??g~H_[]}b@K~@Ha}
ejYZBD@AELb`PdilPJqbPrJIJEJJJJZKZKJJUJ[RccrHii[[zF@HjZifjih@bXZ@@@ !Bmwvw@oy?m?vw?[\B?g~w?_y?bOvw__y?b@Jw?Oy?bOvw__x@mwvw__y??g~w?Oy?mwu??gvHbGvw__y??g~H_[]}b@K~@Ha}
ejYZBD@AELb`PdilPJqbPrJIJEJJJJZKZKJJUJ[RccrHii[[zF@HjZifjih@bXZ@@@ !Bmwvw@oy?m?vw?[\B?g~w?_y?bOvw__y?b@Jw?Oy?bOvw__x@mwvw__y??g~w?Oy?mwu??gvHbGvw__y??g~H_[]}b@K~@Ha}
ejYZBD@AELb`PdilPJqbPrJIJEJJJJZKZKJJUJ[RccrHii[[zF@HjZifjih@bXZ@@@ !Bmwvw@oy?m?vw?[\B?g~w?_y?bOvw__y?b@Jw?Oy?bOvw__x@mwvw__y??g~w?Oy?mwu??gvHbGvw__y??g~H_[]}b@K~@Ha}
ejYZBD@AELb`PdilPJqbPrJIJEJJJJZKZKJJUJ[RccrHii[[zF@HjZifjih@bXZ@@@ !Bmwvw@oy?m?vw?[\B?g~w?_y?bOvw__y?b@Jw?Oy?bOvw__x@mwvw__y??g~w?Oy?mwu??gvHbGvw__y??g~H_[]}b@K~@Ha}
ejYZBD@AELb`PdilPJqbPrJIJEJJJJZKZKJJUJ[RccrHii[[zF@HjZifjih@bXZ@@@ !Bmwvw@oy?m?vw?[\B?g~w?_y?bOvw__y?b@Jw?Oy?bOvw__x@mwvw__y??g~w?Oy?mwu??gvHbGvw__y??g~H_[]}b@K~@Ha}

**Comment by vaitkus** [comment]
Issue seems to be resolved in commits da5d1fcfb89b267543419d2a54507d9831b62630 and 020a2d99fad7a420784cf421ff40b058e94959a3.

**Comment by thsa** [comment]
Hallo Antanas,

Sorry for not reacting otherwise. Thanks for the hint. This was, of course, easy to fix. Currently, I have lot of things to do. I don’t remember, whether I told you that Modest and myself have founded a company to provide cheminformatics services and products. The current focus is on ultra-large combinatorial space searches, 2D and 3D. We believe that there is a big need in pharmaceutical research worldwide. I also extended the molviewer to e.g. support 3D-devices as XR-glasses and 3D-TVs. Currently, I am working on ribbons and cartoons for proteins…

Best wishes,

Thomas

**Comment by vaitkus** [comment]
> Currently, I have lot of things to do. I don’t remember, whether I told you that Modest and myself have founded a company to provide cheminformatics services and products. The current focus is on ultra-large combinatorial space searches, 2D and 3D. We believe that there is a big need in pharmaceutical research worldwide. I also extended the molviewer to e.g. support 3D-devices as XR-glasses and 3D-TVs. Currently, I am working on ribbons and cartoons for proteins…

This sounds exciting indeed! I did not mean to bother you too much with my last comment, but only to note for future  reference that the GitHub issue can most likely be closed as completed. :)
