### ISSUE TITLE
Angle in bonds

### ISSUE THREAD

**Issue by lpatiny** [Actelion/openchemlib#12]
When you draw a molecule with the single bond option just by using one click the first bond is horizontal and the next bonds are not 120 degree angle.

Is this the expected behaviour ?

![image](https://cloud.githubusercontent.com/assets/1484241/20037490/44aa6d38-a420-11e6-8f7d-7484f7fa3cca.png)

**Comment by rufenerc** [comment]
Resolved in latest OCL-js
