### ISSUE TITLE
FXUIHelper question

### ISSUE THREAD

**Issue by BobHanson** [Actelion/openchemlib#120]
Q: Why is file opening disabled in FXUIHelper?

	public File openChemistryFile(boolean isReaction) {
		return null;
/*		return isReaction ?
				FileHelper.getFile(mDrawArea, "Please select a reaction file",
						FileHelper.cFileTypeRXN | CompoundFileHelper.cFileTypeRD)
				: FileHelper.getFile(mDrawArea, "Please select a molecule file",
				FileHelper.cFileTypeMOL | CompoundFileHelper.cFileTypeMOL2);
*/	}

This method is called by GeneralEditorArea.openReaction(), from GeneralEditorArea.eventHappened(GenericActionEvent). Or does FXEditorArea not have a popup menu or toolbar?

**Comment by thsa** [comment]
Bob, thank you for the message. This is a valid question. It seems that this was an oversight and was not noticed, because evidently the FX editor is not used often in reaction mode. I have implemented the method now...

**Comment by BobHanson** [comment]
Yes. I saw that and have synchronized to that point in OCL-SwingJS.

Note that there is nothing in OCL-SwingJS that would have any downside on
OCL itself. Provided I did the manual sync correctly.

I have not changed any of the basic functionality, though I have added some
new functionality -- InChI and CDX and some options to create
molecule-sized images and display hydrogens as a chemist would -- that I
need for my IUPAC project.

Note that I pulled the file handling for onReaction() out of generic in
order to allow it to be asynchronous or not. I just wanted to do only the
most minimal changes in the fx package. So that's a tiny new inner class
there. A bonus is that it returns the processing logic back to generic,
just handling the File object retrieval differently in FX and Swing.
Actually both of these could be asynchronous, but I have kept that in the
Swing side.

Ideally, of course, we would merge and collaborate. You would have the
benefit of full JavaScript functionality for everything in OCL except FX,
and I would have a more appropriate way of managing my fork. I know you
already have that to a point in Luc's implementation, but I don't know that
that has all the file handling and dialogs and such. I think it's rather
minimal. Just a thought.

Note that it was a single update, because last Monday I overlayed your
latest snapshot onto OCL-SwingJS and just patched in the various changes I
made by comparing versions. Then I pushed the changes. So I think if you
look, there are no conflicts if you wanted to try pulling my fork to a new
SwingJS branch of openchemlib.


I do have a question though. Why did you deprecate JDrawing... classes?
Because of FX or because you don't intend to support Swing anymore?

I'd like to undeprecate those. To me they are very useful. Note that I use
the View class to set up image creation and also for testing. It's really a
nice interface. I think it is what Luc is using, though I suppose he had to
totally recreate it in pure JavaScript. I guess I don't know how he keeps
his JavaScript up to date. You were busy last year! But I see Maven pulls
on his Java project. I don't have the problem, since I can keep this all as
one codebase. Or could.


Bob

**Comment by thsa** [comment]
Bob, many thanks for the proposal to merge, but you have to give me some time to play around. Currently, I am under water with some other activities, which I need to finish first. Regarding the JDrawing... classes: Swing will be the main OpenChemLib UI framework for me, because I use it as part of DataWarrior. These classes are deprecated for another reason: About two years ago the editor architecture was changed to complete separate editor logic from specific UI-framework code by defining generic UI elements and events. Then, there are two packages, 'swing' and 'fx', which implement these generic UI objects and create thin Swing- and FX-layers. Luc's new editor implementation uses the same generic UI classes and puts a JS layer on top of it. The new Swing editor uses the com.actelion.research.gui.editor.Swing... classes. The old JDrawing... classes are neither updated nor used anymore.

**Comment by BobHanson** [comment]
I understand. I also found a nasty bug in the InChI to 2d business. So best
if you didn't look yet anyway.  ;)

I'll check into how the editor manages its view. I do think there is a role
for a lightweight nondeprecated view-only non-editor mode. I'm using
JDrawing for creating PNG images that are trimmed to a given standard
molecule size. We use this for our IUPAC processing, and it is also proving
quite useful for testing. But there should be a generic way of doing all of
that. This was just the easiest way I could think of.

I hope to have InChI to 2d and 2d/3d to InChI working later today.

Bob
