### ISSUE TITLE
Java source/target version 1.8 is required instead of the declared 1.6

### ISSUE THREAD

**Issue by vaitkus** [Actelion/openchemlib#51]
The _build.xml_ file declares that Java 1.6 should be used, however, due to the recent additions in commit [40d27cf](https://github.com/Actelion/openchemlib/commit/434decaddc7f6c2953e2e0a924b7ac525e0f639d) this is no longer sufficient and version 1.8 has to be used instead. The unsupported code involves the usage of streams in the "InteractionDistanceStatistics.java" class, i.e.:
https://github.com/Actelion/openchemlib/blob/2682d6d84b2ac64e3ab32ac730fe8ef8ad3eab9c/src/main/java/com/actelion/research/chem/interactionstatistics/InteractionDistanceStatistics.java#L229

The problem is also present in the latest tag release (openchemlib-2019.8.0).

**Comment by artaius** [comment]
Dear Antanas,
Java is now set to 1.8 in build.xml.
Best,
Roman

**Comment by vaitkus** [comment]
Thanks!
