### ISSUE TITLE
Issue parsing an organometallic complex SMILES

### ISSUE THREAD

**Issue by felipe-imanishi** [Actelion/openchemlib#72]
This issue was found while using `openchemlib-js` but it seems that it is related to `openchemlib` and not the js part of it.

https://github.com/cheminfo/openchemlib-js/issues/130

We have this canonical SMILES generated by RDKIT `CNc1ccccc1-c1[c-]cccc1.COc1ccc(OC)c(P(C2CCCCC2)C2CCCCC2)c1-c1c(C(C)C)cc(C(C)C)cc1C(C)C.CS(=O)(=O)O.[Pd]` that fails to render in openchemlib. If we remove the negatively charged carbon (the - in the [c-]), it renders but it is then incorrect.

Is there a limitation here or is this known?

The original smiles (before being canonicalized by RDKIT) `CC(C)C1=CC(=C(C(=C1)C(C)C)C2=C(C=CC(=C2P(C3CCCCC3)C4CCCCC4)OC)OC)C(C)C.CNC1=CC=CC=C1C2=CC=CC=[C-]2.CS(=O)(=O)O.[Pd]` does render, but because we are using rdkit as our standardization tool, it is not possible for us to use this smiles.

Thank you!

Image below is from chemdraw. It shows both smiles mentioned plotted.
The first one is for smiles `CNc1ccccc1-c1[c-]cccc1.COc1ccc(OC)c(P(C2CCCCC2)C2CCCCC2)c1-c1c(C(C)C)cc(C(C)C)cc1C(C)C.CS(=O)(=O)O.[Pd`] and the second one for smiles `CC(C)C1=CC(=C(C(=C1)C(C)C)C2=C(C=CC(=C2P(C3CCCCC3)C4CCCCC4)OC)OC)C(C)C.CNC1=CC=CC=C1C2=CC=CC=[C-]2.CS(=O)(=O)O.[Pd]`.

![image](https://user-images.githubusercontent.com/81549607/172942077-f1e72d93-1491-45d1-b805-94015573a692.png)

**Comment by felipe-imanishi** [comment]
Pinging @thsa in case you missed.

**Comment by lpatiny** [comment]
Openchemlib seems not to be able to deal with `c1[c-]cccc1` or `c1[c-]ccc1` (cylopentadienyl anion) that seems correct. It is always annoying when the charge (2 electrons) may be part of the aromaticity or not.

On the other hand `c1[c+]c1` and `c1[c+]ccccc1` are accepted.
