### ISSUE TITLE
Problem with colors

### ISSUE THREAD

**Issue by lpatiny** [Actelion/openchemlib#76]
@thsa i have a problem of rendering the stereobonds in openchemlib-js

It seems to me that the red and blue colors are inverted

![2022-08-15 12 27 06](https://user-images.githubusercontent.com/1484241/184619802-58dd8570-6bba-489e-a9c1-5e046da31564.gif)

https://github.com/zakodium-oss/react-ocl/issues/16#issuecomment-1214870400

**Comment by thsa** [comment]
In the Java version it seems fine. It must be an issue of the JS adaption. Anyway, for the editor I strongly suggest to move to the new Editor concept. The old one is deprecated, not updated anymore and missed new features, e.g. regarding substructure search.

**Comment by targos** [comment]
I'll have a look at the JS adaptation to see if there's an obvious fix.
We intend to use the new Editor concept but it will take some time.

**Comment by targos** [comment]
This is fixed in OCL-js
