### ISSUE TITLE
SVGDepictor extends AbstractDepictor<Void>

### ISSUE THREAD

**Issue by BobHanson** [Actelion/openchemlib#84]
Please add \<Void\> after AbstractDepictor for SVGDepictor, as it has no graphics context, and this removes the warning:

Type safety: The method validateView(Object, GenericRectangle, int) belongs to the raw type AbstractDepictor. References to generic type AbstractDepictor<T> should be parameterized

(Always hoped I'd find a use for Void!!)

**Comment by thsa** [comment]
done
