### ISSUE TITLE
error in double bond side logic

### ISSUE THREAD

**Issue by BobHanson** [Actelion/openchemlib#85]
oops. Not honoring the aromatic nature of that central ring. 

![image](https://user-images.githubusercontent.com/17748315/216068374-134d630e-db8f-4741-9ed6-af083dfab064.png)

I think the algorithm used there is not taking into account the fact that the central ring has three explicit double bonds. Any such aromatic ring should have the guide point for the double bond offset at the center of the ring. It's only rings with two or fewer double bonds that need anything more complicated than that.

**Comment by thsa** [comment]
is fixed

**Comment by BobHanson** [comment]
Please attach the commit associated with this issue. Just use the word "commit" followed by the full commit ID.

**Comment by BobHanson** [comment]
Thank you! It is great to see that the logic is easily adaptable. Very smart! 

I would like to suggest a more fundamental adjustment. Note that nothing in this method relates to anything else in AbstractDepictor -- no drawing, not sizing, no colors, nothing specific to drawing. 

Thus, I suggest that it be moved to ExtendedMolecule (and have done so in [OCL-SwingJS](https://github.com/BobHanson/OCL-SwingJS/commit/9cbd2c8540d66abb7e4475f05a6e5f9c3a2eccb9)), in conformance with that class's stated purpose: "ExtendedMolecule handles secondary, i.e. calculated molecule information. Most important are the directly connected atoms and bonds of every atom, information about rings and whether they are aromatic, and some atom properties that depend on their near neighbors. This calculated information is cached in helper arrays and stays valid as long as the molecule's primary information is not changed.

This change allows use of the method outside of the graphical depiction context (for example, when writing CDXML files).

**Comment by thsa** [comment]
Sorry, I just have realized the suggestion and moved the method mpPreferredSide() as you suggested to ExtendeMolecule as getPreferredDoubleBondSide()
