### ISSUE TITLE
SmilesParser is not idempotent

### ISSUE THREAD

**Issue by targos** [Actelion/openchemlib#92]
Once it's been called with `readStereoFeatures = true`, subsequent calls with `readStereoFeatures = false` don't work as expected:

```java
SmilesParser parser = new SmilesParser();
StereoMolecule molecule = new StereoMolecule(0, 0);
String smiles = "Cl/C=C/Br";

parser.parse(molecule, smiles.getBytes(), true, false);
System.out.println(molecule.getIDCode()); // gC`DAbZHRVX@

parser.parse(molecule, smiles.getBytes(), true, true);
System.out.println(molecule.getIDCode()); // gC`DAbZHRVXRP

parser.parse(molecule, smiles.getBytes(), true, false);
System.out.println(molecule.getIDCode()); // gC`DAbZHRVXRP
```

Moreover, if we call it with `createCoordinates = false`, it will always print ``gC`DAbZHRVXRP``, regardless of the value of `readStereoFeatures`.

**Comment by targos** [comment]
@thsa What do you think?

**Comment by thsa** [comment]
@targos Hi Michael, sorry for the late response. I didn't notice the question. I have just fixed it. In this situation the StereoMolecule was re-using the Canonizer from previous runs and taking parity information from there.

Concerning createCoordinates = false: You cannot use molecule.getIDCode(), if the Molecule has valid parities and does not contain atom coordinates. Thus, after Smiles parsing with createCoordinates = false we have this sutuation and it will always print 'null' now. molecule.getIDCode() is a convenient method, which only works, if a Canonizer was created and used during the ensureHelperArrays() call.
